### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by b4zz4** [guyc/scadtrace#1]
make
convert artwork.jpg artwork.bmp
potrace --svg artwork.bmp
./svgtoscad.py artwork.svg
Traceback (most recent call last):
  File "./svgtoscad.py", line 115, in <module>
    svg = Svg(filename)
  File "/home/eduardo/src/scadtrace/svg.py", line 153, in **init**
    self.width = int(svgNode.attributes["width"].value.rstrip("pt"))
ValueError: invalid literal for int() with base 10: '400.000000'
make: **\* [all] Error 1

**Comment by guyc** [comment]
First guess would be that it is a python 2 vs python 3 incompatibility.  I'll have a look when I get a chance.

**Comment by guyc** [comment]
Nope it wasn't python3.  The output format from potrace has changed slightly.  I've updated the script to accommodate that, along with a bunch of other small improvements to both documentation and code.  I haven't touched this code since I got it developed enough to generate my openscad models and it certainly needed a bit of a tidy up.  Let me know if you have any other problems.

**Comment by b4zz4** [comment]
> make
> convert artwork.jpg artwork.bmp
> potrace --svg artwork.bmp
> ./svgtoscad.py --triangle triangle --angle=60 --rotate artwork.svg
> ['triangle', '-z', '-q', '-p', '/tmp/triangle.1.poly']
> Traceback (most recent call last):
>   File "./svgtoscad.py", line 174, in <module>
>     mesh = tri.polyToMesh(qp,str(index))
>   File "/home/eduardo/src/scadtrace/quake.py", line 26, in polyToMesh
>     result = subprocess.call(cmd)
>   File "/usr/lib/python2.7/subprocess.py", line 522, in call
>     return Popen(_popenargs, *_kwargs).wait()
>   File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> make: **\* [scad] Error 1

i have triangle compilater

El 14/03/15 a las 03:39, Guy Carpenter escibió:

> Nope it wasn't python3. The output format from potrace has changed
> slightly. I've updated the script to accommodate that, along with a
> bunch of other small improvements to both documentation and code. I
> haven't touched this code since I got it developed enough to generate
> my openscad models and it certainly needed a bit of a tidy up. Let me
> know if you have any other problems.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/guyc/scadtrace/issues/1#issuecomment-80008688.

## 

http://ba.zza.pl
gpg: http://ba.zza.pl/bazza.asc

**Comment by guyc** [comment]
The path to the triangle executable should be set in the Makefile here:

```
# set TRIANGLE to the binary for quake triangle
# see: http://www.cs.cmu.edu/~quake/triangle.html
TRIANGLE = triangle/triangle
```

Looking at your output, your Makefile must have something like 'TRIANGLE=triangle'", with no path, and triangle appears not to be in the search path.  Try setting TRIANGLE to the full path of the triangle binary, which might be something like "TRIANGLE=/home/eduardo/src/triangle/triangle"
